notifications:
  slack: wtsi-cgpit:ptUMR1tkNyZJYd9TpGoss8WR
  email: false

sudo: false

language: ruby

services:
  - docker

script:
 - echo 'Build and check docker image'
 - docker build -t allelec .
 - docker images | grep -c allelec
 - echo 'Verify program(s) from this repo'
 - docker run -t --rm allelec alleleCounter -v
 - docker run -t --rm allelec alleleCounter.pl -v
